name: Send GH PR metrics to Monday Board

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string
      repo-name:
        required: true
        type: string

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      # Find the PR associated with this push, if there is one.
      - name: Get PR number
        uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: all

      - name: main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.find-pr.outputs.pr }}
          OWNER: ${{ inputs.repo-owner }}
          REPO: ${{ inputs.repo-name }}
        run: |
          echo PR Number : $PR_NUMBER
          echo Owner     : $OWNER
          echo Repo      : $REPO
          wget https://raw.githubusercontent.com/saularraffi/churn-wiz/main/main.py && \
          python main.py -o $OWNER -r $REPO -pr $PR_NUMBER -gt $GH_TOKEN
