name: Send GH PR metrics to Monday Board

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string
      repo-name:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Find the PR associated with this push, if there is one.
      - name: Get PR number
        uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: all

      - name: Get Total Churn
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.find-pr.outputs.pr }}
          OWNER: ${{ inputs.repo-owner }}
          REPO: ${{ inputs.repo-name }}
        run: |
          wget https://raw.githubusercontent.com/saularraffi/github-metrics/main/gh_churn_metrics.py
          totalChurn="$(python gh_churn_metrics.py -o $OWNER -r $REPO -pr $PR_NUMBER -gt $GH_TOKEN)"
          echo "TOTAL_CHURN="$totalChurn >> $GITHUB_ENV

      - name: Log Results
        run: |
          echo "Total churn: $TOTAL_CHURN lines"
