name: Workflow Test

on:
  push:
    branches:
      - main

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      # - env:
      #     GH_TOKEN: ${{ secrets.MY_TOKEN }}
      - run: git blame README.md
