name: Workflow Test

on:
  push:
    branches:
      - main

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ inputs.repo-owner }}
          REPO: ${{ inputs.repo-name }}
          PR_NUMBER: ${{ steps.find-pr.outputs.pr }}
        run: |
          echo token - $GH_TOKEN
          echo owner - $OWNER
          echo repo - $REPO
          echo pr - $PR_NUMBER
