name: Workflow Test

on:
  push:
    branches:
      - main

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      # Find the PR associated with this push, if there is one.
      - name: Get PR number
        uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: all

      - name: main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.find-pr.outputs.pr }}
        run: |
          echo token - $GH_TOKEN
          echo pr - $PR_NUMBER
